Transform: AWS::Serverless-2016-10-31

Resources:
  LayerBase:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/base

  ParameterLayerArnBase:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Golden/Layer/Base
      Type: String
      Value: !Ref LayerBase

  ParameterLayerArnScraping:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /Golden/Layer/Scraping
      Type: String
      Value: !Ref LayerScraping
