Transform: AWS::Serverless-2016-10-31

Resources:
  StackLayerBase:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./layer.yml
      Parameters:
        ContentUri: layers/base
        ParameterName: /LayerTemplate/Layer/Base
